// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repo

import (
	"context"
	"olivine/internal/repo/object"
	"sync"
)

// Ensure, that StorageMock does implement Storage.
// If this is not the case, regenerate this file with moq.
var _ Storage = &StorageMock{}

// StorageMock is a mock implementation of Storage.
//
//	func TestSomethingThatUsesStorage(t *testing.T) {
//
//		// make and configure a mocked Storage
//		mockedStorage := &StorageMock{
//			GetFunc: func(ctx context.Context, k string) (object.Object, error) {
//				panic("mock out the Get method")
//			},
//			PruneFunc: func(contextMoqParam context.Context) error {
//				panic("mock out the Prune method")
//			},
//			SetFunc: func(ctx context.Context, param SetParam) error {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedStorage in code that requires Storage
//		// and then make assertions.
//
//	}
type StorageMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, k string) (object.Object, error)

	// PruneFunc mocks the Prune method.
	PruneFunc func(contextMoqParam context.Context) error

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, param SetParam) error

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// K is the k argument value.
			K string
		}
		// Prune holds details about calls to the Prune method.
		Prune []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Param is the param argument value.
			Param SetParam
		}
	}
	lockGet   sync.RWMutex
	lockPrune sync.RWMutex
	lockSet   sync.RWMutex
}

// Get calls GetFunc.
func (mock *StorageMock) Get(ctx context.Context, k string) (object.Object, error) {
	if mock.GetFunc == nil {
		panic("StorageMock.GetFunc: method is nil but Storage.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		K   string
	}{
		Ctx: ctx,
		K:   k,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, k)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedStorage.GetCalls())
func (mock *StorageMock) GetCalls() []struct {
	Ctx context.Context
	K   string
} {
	var calls []struct {
		Ctx context.Context
		K   string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Prune calls PruneFunc.
func (mock *StorageMock) Prune(contextMoqParam context.Context) error {
	if mock.PruneFunc == nil {
		panic("StorageMock.PruneFunc: method is nil but Storage.Prune was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockPrune.Lock()
	mock.calls.Prune = append(mock.calls.Prune, callInfo)
	mock.lockPrune.Unlock()
	return mock.PruneFunc(contextMoqParam)
}

// PruneCalls gets all the calls that were made to Prune.
// Check the length with:
//
//	len(mockedStorage.PruneCalls())
func (mock *StorageMock) PruneCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockPrune.RLock()
	calls = mock.calls.Prune
	mock.lockPrune.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *StorageMock) Set(ctx context.Context, param SetParam) error {
	if mock.SetFunc == nil {
		panic("StorageMock.SetFunc: method is nil but Storage.Set was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Param SetParam
	}{
		Ctx:   ctx,
		Param: param,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(ctx, param)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedStorage.SetCalls())
func (mock *StorageMock) SetCalls() []struct {
	Ctx   context.Context
	Param SetParam
} {
	var calls []struct {
		Ctx   context.Context
		Param SetParam
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}
