// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"github.com/mazrean/kessoku"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/trace"
	"net/http"
	"olivine/internal/data"
	"olivine/internal/repo"
	"olivine/internal/server"
	"olivine/internal/service"
	"olivine/internal/service/cmd"
)

func NewApp(config *data.Config) (*App, error) {
	storage := kessoku.Bind[repo.Storage](kessoku.Provide(repo.NewStorage)).Fn()()
	tracer := kessoku.Bind[trace.Tracer](kessoku.Provide(func() trace.Tracer {
		return otel.Tracer("olivine")
	})).Fn()()
	var err error
	aof, err := kessoku.Bind[service.AOF](kessoku.Provide(func(cfg *data.Config) (service.AOF, error) {
		if !cfg.AOFEnabled {
			return nil, nil
		}
		return service.NewAOF(cfg, AOFPath)
	})).Fn()(config)
	if err != nil {
		var zero *App
		return zero, err
	}
	val := kessoku.Provide(cmd.NewCommands).Fn()(storage, tracer)
	worker := kessoku.Bind[service.Worker](kessoku.Provide(service.NewWorker)).Fn()(config, aof, storage)
	handler := kessoku.Bind[server.Handler](kessoku.Provide(func(cfg *data.Config, aof service.AOF, tracer trace.Tracer, cmds []cmd.Command) server.Handler {
		middlewares := []server.Middleware{}
		if cfg.AOFEnabled {
			middlewares = append(middlewares, server.NewAOFMiddleware(aof))
		}
		return server.NewHandler(tracer, cmds, middlewares...)
	})).Fn()(config, aof, tracer, val)
	restorer := kessoku.Bind[server.Restorer](kessoku.Provide(func(cfg *data.Config, aof service.AOF, handler server.Handler) server.Restorer {
		if !cfg.AOFEnabled {
			return nil
		}
		return server.NewRestorer(aof, handler)
	})).Fn()(config, aof, handler)
	server0 := kessoku.Bind[server.Server](kessoku.Provide(server.NewServer)).Fn()(handler, restorer)
	app := kessoku.Provide(func(cfg *data.Config, worker service.Worker, server server.Server) *App {
		return &App{cfg: cfg, worker: worker, server: server, httpsrv: &http.Server{Addr: "localhost:6060"}}
	}).Fn()(config, worker, server0)
	return app, nil
}
