// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"github.com/mazrean/kessoku"
	"olivine/internal/data"
	"olivine/internal/repo"
	"olivine/internal/server"
	"olivine/internal/service"
	"olivine/internal/service/cmd"
)

func NewApp(config *data.Config) (*App, error) {
	var err error
	aof, err := kessoku.Bind[service.AOF](kessoku.Provide(func(cfg *data.Config) (service.AOF, error) {
		if !cfg.AOFEnabled {
			return nil, nil
		}
		return service.NewAOF(cfg, AOFPath)
	})).Fn()(config)
	if err != nil {
		var zero *App
		return zero, err
	}
	handler := kessoku.Bind[server.Handler](kessoku.Provide(func(cfg *data.Config, aof service.AOF) server.Handler {
		middlewares := []server.Middleware{}
		if cfg.AOFEnabled {
			middlewares = append(middlewares, server.NewAOFMiddleware(aof))
		}
		return server.NewHandler(cmd.NewCommands(repo.NewStorage()), middlewares...)
	})).Fn()(config, aof)
	restorer := kessoku.Bind[server.Restorer](kessoku.Provide(func(cfg *data.Config, aof service.AOF, handler server.Handler) server.Restorer {
		if !cfg.AOFEnabled {
			return nil
		}
		return server.NewRestorer(aof, handler)
	})).Fn()(config, aof, handler)
	server0 := kessoku.Bind[server.Server](kessoku.Provide(server.NewServer)).Fn()(handler, restorer)
	app := kessoku.Provide(func(cfg *data.Config, aof service.AOF, srv server.Server) *App {
		return &App{cfg: cfg, aof: aof, srv: srv}
	}).Fn()(config, aof, server0)
	return app, nil
}
